compatibility_date = "2023-10-16"
main = "src/index.ts"
name = "r2-webdav"

compatibility_flags = ["nodejs_compat"]

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
[[r2_buckets]]
binding = "bucket" # <~ valid JavaScript variable name
bucket_name = "webdav"

# Bind a KV Namespace for storing user accounts
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv/
# Create with: wrangler kv namespace create users
[[kv_namespaces]]
binding = "users"
id = "927d910e401b40db89588ae6614ce868"

# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
head_sampling_rate = 1
